export enum PostType {
  Image = 'fanzposters',
  Announcement = 'Announcement',
  ProjectAnnouncement = 'ProjectAnnouncement',
  Trailer = 'Trailer',
  Anniversary = 'Anniversary',
  Birthday = 'Birthday',
  MovieDetails = 'MovieDetails',
  CharacterIntroduction = 'CharacterIntroduction',
  Countdown = 'Countdown',
  Filmography = 'Filmography',
  Awards = 'Awards',
  Celebrity = 'Celebrity',
  BoxOffice = 'BoxOffice',
  Trivia = 'Trivia',
}